package com.deloitte.pokedex.util

const val BASE_URL_POKEMON_API = "https://pokeapi.co/api/v2/"
const val POKEMON_DETAILS = "POKEMON_DETAILS"
const val HP = "hp"
const val SPEED = "speed"
const val ATTACK = "attack"
const val DEFENSE = "defense"
const val SPECIAL_ATTACK = "special-attack"
const val SPECIAL_DEFENCE = "special-defense"
const val FRONT_DEFAULT = "FRONT DEFAULT"
const val BACK_DEFAULT = "BACK DEFAULT"
const val FRONT_FEMALE = "FRONT FEMALE"
const val BACK_FEMALE = "BACK FEMALE"
const val FRONT_SHINY = "FRONT SHINY"
const val BACK_SHINY = "BACK SHINY"
const val FRONT_SHINY_FEMALE = "FRONT SHINY FEMALE"
const val BACK_SHINY_FEMALE = "BACK SHINY FEMALE"
